### ISSUE TITLE
Build problems with Kickass version 4.x

### ISSUE THREAD

**Issue by djtulan** [hbekel/xlink#1]
Hi Hennig!

I tried to build xlink described as on your homepage, but with 4.3 i wasn't lucky.
I had to switch back to the old 3.41. I tried even the tool kickass 3to4 converter, but no success.
Maybe you should make a note in your descriptions.

best regards Robert

**Comment by hbekel** [comment]
Hi Robert,

Thanks for the notice. I hadn't noticed yet that Kickassembler had a new major release introducing breaking changes. I'll add a notice tomorrow. Maybe I can make it work for both versions, but I will have to look into that more deeply.

Regards,
Henning

**Comment by hbekel** [comment]
After looking into KickAssembler 4 I have decided not to port the existing software. A lot of features have been removed that my code relies on, and porting would include the risk of introducing new bugs for no real reason.

Unfortunately, Kickassember misses a proper --version option, so there is not easy way to bail out from the Makefile.

I've added explicit version requirements to the website.
