### ISSUE TITLE
ROM based server läuft problemlos - RAM based server: C64 hängt sich auf

### ISSUE THREAD

**Issue by richy64** [hbekel/xlink#2]
Hallo Henning,
mein Name ist Richard Kotte, vor gefühlt einem Jahr oder mehr war ich auf der DoReCo und hatte ich einen XLINK-Bausatz von Dir erstanden.
 
Der Aufbau der XLINK-Platine,
das Bespielen des Controllers mit xlink-firmware-1.3.hex,
die Einrichtung von XLINK auf meinem Windows-Rechner ging problemlos von statten.
Ein Kernal habe ich erzeugt, auf Eprom gebrannt und in meinem C64C mit 250469 Board installiert.
ROM based XLINK läuft problemlos. Programme können per Kommandozeile übertragen und gestartet werden.
 
 
Allerdings habe ich festgestellt, dass die RAM based server-Version nicht sauber arbeitet.
Den RAM based server habe ich erstellt über Kommandozeile: xlink server server.prg
als auch über Bootstrapping-Methode, beide führen zu gleichem Ergebnis:
Auf dem C64 verwende ich den Standard-Commodore-Kernel; wenn ich nun die server.prg auf dem C64 starte und auf der Kommandozeile: xlink run
ausführe,
stürzt der C64 reproduzierbar ab: Entweder hört der Cursor auf zu blinken oder der Bildschirm wird gelöscht und man landet bei READY (als wenn man Run/Stop-Restore drückt).

Auffällig ist noch, das xlink identify
beim ROM based server zurückmeldet: XLINK 1.0 C64 ROM $F547-$FB42
und beim RAM based server zurückmeldet: XLINK 1.0 C64 RAM $8040-$836A
Die RAM based server Version ist offensichtlich erheblich kürzer, ist das gewollt bzw. vielleicht hat das mit dem Problem zu tun?
 
Henning, könnest Du das bei Gelegenheit mal bei Dir probieren/gegenchecken? Vielen Dank.
Ansonsten, falls es bei Dir nicht reproduzierbar ist, würde ich mal zu einer DoReCo kommen und es anbieten vorzuführen.
 
Danke und viele Grüße,
Richard Kotte

**Comment by hbekel** [comment]
I have never been able to reproduce this behavior so I'm closing this issue.
